config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :containers
  resources :items

  scope module: :paginates do
    resources :paginated_containers, only: :index
  end

  root to: 'containers#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/container.rb
class Container < ApplicationRecord
  validates_presence_of :name
end

app/models/results_paginator.rb
class ResultsPaginator
  def initialize(results, current_page: 1, per_page: 9)
    set_results(results)
    set_total_entries
    set_per_page(per_page)
    set_current_page(current_page)
  end

  def empty_results?
    @results.empty?
  end

  def displayed_page_count
    empty_results? ? 0 : @results.paginate(page: 1, per_page: @per_page).total_pages
  end

  def get_current_page
    @current_page
  end

  def items
    paginated_results.to_json
  end

  def paginated_results
    @results.order(updated_at: :desc).paginate(page: @current_page, per_page: @per_page)
  end

  def set_current_page(current_page)
    current_page = current_page.to_i
    @current_page = if (current_page > displayed_page_count && !displayed_page_count.zero?)
      displayed_page_count
    else
      current_page.zero? ? 1 : current_page
    end
  end

  def set_per_page(per_page)
    @per_page = per_page.to_i
  end

  def set_results(results)
    @results = results
  end

  def set_total_entries
    @results.count
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
  before_action :get_container, only: [:edit, :update, :destroy]

  def index
    @paginator = ResultsPaginator.new(Container.all)
  end

  def new
    render json: { new_record: Container.new.as_json(only: [:name, :description]) }
  end

  def edit
    render json: { record: @container.as_json(only: [:name, :description])}
  end

  def update
    if @container.update(container_params)
      @paginator = ResultsPaginator.new(Container.all, current_page: params[:active_page].presence)
      render json: { containers: @paginator.items, active_page: @paginator.get_current_page, total_pages: @paginator.displayed_page_count, message: "Successfully updated", transaction_status: "success" }, status: :ok
    else
      render json: { errors: @container.errors.full_messages.join("<br> ") }, status: :unprocessable_entity
    end
  end

  def create
    new_container = Container.new(container_params)
    if new_container.save
      @paginator = ResultsPaginator.new(Container.all, current_page: params[:active_page].presence)
      render json: { containers: @paginator.items, active_page: @paginator.get_current_page, total_pages: @paginator.displayed_page_count, message: "Successfully created", transaction_status: "success" }, status: :ok
    else
      render json: { errors: new_container.errors.full_messages.join("<br> ") }, status: :unprocessable_entity
    end
  end

  def destroy
    if @container.destroy
      @paginator = ResultsPaginator.new(Container.all, current_page: params[:active_page].presence)
      render json: { containers: @paginator.items, active_page: @paginator.get_current_page, total_pages: @paginator.displayed_page_count, message: "Successfully destroyed", transaction_status: "success" }, status: :ok
    else
      render json: { message: @container.errors.full_messages.join("<br> "), transaction_status: "danger" }, status: :unprocessable_entity
    end
  end

  private
  def get_container
    @container = Container.find(params[:id])
  end

  def container_params
    params.require(:record).permit(:name, :description)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  end
end

app/controllers/paginates/paginated_containers_controller.rb
class Paginates::PaginatedContainersController < ApplicationController
  def index
    @paginator = ResultsPaginator.new(Container.all, current_page: params[:current_page])
    render json: {containers: @paginator.paginated_results, active_page: @paginator.get_current_page}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/containers/index.html.slim
.container-listing data-containers=@paginator.items data-total-pages=@paginator.displayed_page_count data-authenticity-token=form_authenticity_token

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | ReactInventory
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application'
  body.navbar__top_padding
    = render partial: 'layouts/shared/navbar'
    .row.row__no_right_margin
      = render partial: 'layouts/shared/sidebar'
      .col-lg-9.col-md-9.padded-content
        = yield

app/views/layouts/shared/_navbar.html.slim
.row.row__no_right_margin
  .navbar.navbar-default.navbar-fixed-top
    .container-fluid
      .navbar-header
        = link_to 'Inventory', root_path, class: 'navbar-brand'

app/views/layouts/shared/_sidebar.html.slim
.col-lg-3.col-md-3
  .list-group
    = link_to 'Containers', root_path, class: "list-group-item list-group-item__unbordered list-group-item__unrounded text-center #{current_page?(root_path) ? 'active' : ''}"
    = link_to 'Items', items_path, class: "list-group-item list-group-item__unbordered list-group-item__unrounded text-center #{current_page?(items_path) ? 'active' : ''}"